name: Migrate Notebooks
on:
  push:
    branches:
      - stage
      - production
  workflow_dispatch:
jobs:
  deploy_to_staging:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Databricks CLI
        run: |
          pip install --user --upgrade databricks-cli
      - name: Migrate Notebooks to Staging
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_STAGING }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_STAGING }}
        run: |
          DBFSFILEPATH="/Shared/notebooks"
          LOCALFILEPATH="notebooks/"
          set -e
          databricks workspace import_dir "$LOCALFILEPATH" "$DBFSFILEPATH" --overwrite
  deploy_to_production:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Databricks CLI
        run: |
          pip install --user --upgrade databricks-cli
      - name: Migrate Notebooks to Production
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_PROD }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
        run: |
          DBFSFILEPATH="/Shared/notebooks"
          LOCALFILEPATH="notebooks/"
          set -e
          databricks workspace import_dir "$LOCALFILEPATH" "$DBFSFILEPATH" --overwrite
